version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: bash